### ISSUE TITLE
Standalone execution

### ISSUE THREAD

**Issue by kilaka** [RitwikSaikia/jsonrpc#11]
I couldn't execute the server as a standalone app.
I tried what was in the main page. See example below.
Perhaps I'm missing some connection initiation code on the server side.
Any idea?
## Server:

public class Main {
    public static void main(String[] args) throws InterruptedException {
        Thread thread = new Thread() {
            @Override
            public void run() {
                JsonRpcExecutor executor = new JsonRpcExecutor();
                SampleIface sampleImpl = new SampleImpl();
                executor.addHandler("sample", sampleImpl, SampleIface.class);
                while(true) {
                    try {
                        Thread.sleep(1000_60_60);
                    } catch (InterruptedException e) {
                        e.printStackTrace();
                    }
                }
            }
        };
        thread.setDaemon(false);
        thread.start();
    }
}
## Client:

public class Test {
    public static void main(String[] args) throws MalformedURLException {
        String url = "http://127.0.0.1:8080/jsonrpc"; 
        HttpJsonRpcClientTransport transport = new HttpJsonRpcClientTransport(new URL(url));
        JsonRpcInvoker invoker = new JsonRpcInvoker();
        SampleIface sample = invoker.get(transport, url, SampleIface.class);
        sample.run(true);
    }
}

**Comment by kilaka** [comment]
Sorry for the lousy spacing. I couldn't make it look like code.

**Comment by RitwikSaikia** [comment]
The library is designed to be agnostic of the transport layer, the Servlet implementation is just a helper class to allow you easily deploy the application under a war.

To host it as a standalone server, you need to figure out the Transport protocol you want to use, e.g. is it over HTTP or plain TCP, or some custom protocol.

i.e. Just implement [JsonRpcServerTransport](https://github.com/RitwikSaikia/jsonrpc/blob/master/jsonrpc-java/src/main/java/org/json/rpc/server/JsonRpcServerTransport.java) interface, and pass it on to **executor.execute()**, as an when u receive ur packets.

e.g. a sample implementation will be

``` java

ServerSocket server = new ServerSocket(8181);

Socket sock;
while((sock = server.accept()) != null) {

executor.execute(new JsonRpcServerTransport() {

    public String readRequest() throws Exception {
       String req;
       // read req from sock, and return.
        return req;
    }

    public void writeResponse(String responseData) throws Exception {
        //  write response to the sock
    }
});

}
```

Similarly the client side has to know how to read and write over the wire, hence needs to implement [JsonRpcClientTransport](https://github.com/RitwikSaikia/jsonrpc/blob/master/jsonrpc-java/src/main/java/org/json/rpc/client/JsonRpcClientTransport.java) and pass it on to the invoker.

The reason it is kept like this is, it gives u a freedom of implementation, whether u want to use java.nio, java.net, netty ..., whatever u like. Since HTTP is the widely used protocol, the implementation is part of the project.

**Comment by RitwikSaikia** [comment]
Just look into the following two test classes for in memory implementation
1. [JsonRpcInvokerTest](https://github.com/RitwikSaikia/jsonrpc/blob/develop/jsonrpc-java/src/test/java/org/json/rpc/client/JsonRpcInvokerTest.java)
2. [JsonRpcExecutorTest](https://github.com/RitwikSaikia/jsonrpc/blob/develop/jsonrpc-java/src/test/java/org/json/rpc/server/JsonRpcExecutorTest.java)

I hope this solves your problem.
